#!/usr/bin/env bash

set -eu

# If a package contains a directory, stow will create a symlink to that
# directory, rather than creating the directory and putting symlinks inside it.
# Normally, this is what we want, but in some cases, we don't want a directory
# to be owned by the package we're installing. Creating those directories first
# if they don't already exist will ensure that doesn't happen.
mkdir -p "$HOME/{.config,.local}"

for package_dir in packages/*/; do
    package="${package_dir%/}"
    package="${package##*/}"
    echo >&2 "Installing $package"
    stow -v -d packages -t "$HOME" -R "$package"
    echo >&2
done
