# Change prefix from control+b to control+a
# control+a control+a types a control+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Left status line shows session name (default)
# Make right status line show window name + pain index + PREFIX (if the prefix key was pressed)
STATUS_RIGHT='#W.#P#{?client_prefix, PR,}'
set -g status-right "$STATUS_RIGHT"

# Make a passthrough toggle
# When the unmap key is pressed,
# only the prefix key will be active until the map key is pressed,
# and the right status line will indicate that passthrough is active.
#
# Unmap
bind \\ set -g key-table passthrough \; \
    set -g status-right "$STATUS_RIGHT PASS"
# Map
bind / set -g key-table root \; \
    set -g status-right "$STATUS_RIGHT"

# Number windows and panes from 1; 0 is so far away.
# prefix+0 therefore should be mapped to window 10.
set -g base-index 1
setw -g pane-base-index 1
bind 0 select-window -t 10

# Use vim keybindings in copy mode
# Copied text will be placed on the Mac OS clipboard.
# brew install reattach-to-user-namespace
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel pbcopy
# Enter still uses tmux's default buffers

# Reload config
# This clobbers tmux's repaint screen key.
# Everyone does it though, and I've never needed to repaint,
# so this is probably fine for now.
bind r source-file ~/.tmux.conf

# Makes escape quicker in vim/nvim
set -g escape-time 10

set -g history-limit 30000
set -g status-keys vi
set -g visual-activity on
set -g visual-silence on
set -g focus-events on
set -gu terminal-features
set -sa terminal-features ',xterm-256color:RGB'
set -sa terminal-features ',xterm-256color:extkeys'
set -g extended-keys on

# prefix+c should still create the window in the session's default path
# Use prefix+control+c to create a window in the current directory.
bind C-c neww -c '#{pane_current_path}'

# Stop PuTTY from beeping when attaching to a tmux session
#set -g terminal-overrides ',xterm*:Cr=\E]12;gray\007,xterm*:indn@'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-urlview'
run -b '~/.tmux/plugins/tpm/tpm'
