version: 2
root-markers:
  - .git/
lint-debounce: 1s
tools:
  markdown-mdformat: &markdown-mdformat
    format-command: 'mdformat --wrap 80 -'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
    lint-stdin: true

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  python-yapf: &python-yapf
    format-command: 'yapf --quiet'
    format-stdin: true

  html-prettier: &html-prettier
    format-command: 'prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser html'

  css-prettier: &css-prettier
    format-command: 'prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser css'

  json-prettier: &json-prettier
    format-command: 'prettier ${--tab-width:tabWidth} --parser json'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  json-jq: &json-jq
    lint-command: 'jq .'

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

languages:
  markdown:
    - <<: *markdown-mdformat

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  python:
    - <<: *python-yapf

  html:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  json:
    - <<: *json-jq
    - <<: *json-fixjson
    # - <<: *json-prettier

  lua:
    - <<: *lua-lua-format

